### ISSUE TITLE
Where are images located?

### ISSUE THREAD

**Issue by oleteacher** [fredrikekelund/grav-plugin-resize-images#10]
Have installed the plugin and configured. Chose GD and Imagick (both installed on server) for conversions. Neither seem to work as cannot see any options to choose images?

I see the image uploaded (both on page and looking in FTP) but see no resized images.

If I do get it working, how do I choose the desired image?

Will the images actually be responsive?

Thanks and sorry for not getting it, very confused.

Susan

**Comment by fredrikekelund** [comment]
Hi! This plugin works by resizing images when pages are saved rather than when a button is clicked in the plugin options panel.

I want to add support for a feature where people can use the terminal to generate "responsive variants" of all existing images in one go, but the best way to generate variations of existing images currently is to go into the admin panel and re-save the pages where those images live. Every time a page is saved (whether it's new or old), this plugin will go through all images (again, whether they are new or old) in that page, check if they have responsive variants and generate new ones if necessary.

Does that makes sense?

**Comment by fredrikekelund** [comment]
Hey @oleteacher, I'm closing this issue for now. Let me know if you need more assistance, though - happy to help!

**Comment by oleteacher** [comment]
No problem, thank you for explaining. Got side tracked with end of school year:)
