### ISSUE TITLE
This is part of the admin plugin now

### ISSUE THREAD

**Issue by Tamriel** [fredrikekelund/grav-plugin-resize-images#16]
The function of this plugin is part of the admin plugin now:
[https://github.com/getgrav/grav-plugin-admin/commit/d53e5b111fead3d32fd5409ff8bc8d6734886515](https://github.com/getgrav/grav-plugin-admin/commit/d53e5b111fead3d32fd5409ff8bc8d6734886515)

**Comment by nerikh** [comment]
Hey,
The resize-images plugin's config page allows to set multiple image sets of widths/heights, however, the admin panel version of this only allows for a single, global setting applied to all images.  Can the admin.yaml or blueprint.yaml be adjusted to allow for multiple sets?

**Comment by Tamriel** [comment]
No, just a single set.

**Comment by nerikh** [comment]
Any plans to add the capability, or do you think the other module will
continue to be needed?


Nils 'Erik' Hendrick
904.710.1478

On May 12, 2018 5:45 PM, "Jan" <notifications@github.com> wrote:

No, just a single set.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/fredrikekelund/grav-plugin-resize-images/issues/16#issuecomment-388585332>,
or mute the thread

**Comment by fredrikekelund** [comment]
Thanks for bringing this to my attention! However, since it looks like this plugin's particular feature isn't part of the core admin yet, I'll close this issue for now
